name: 'pr-notify'
description: 'push PR notifications to slack'
author: 'davidwallacejackson'
inputs:
  users:
    description: 'mapping of Github usernames to slack emails'
    default: '{}'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
